
# host: localhost
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wdi-project-4-api_development


test:
  <<: *default
  database: wdi-project-4-api_test


production:
  <<: *default
  database: wdi-project-4-api_production
  username: wdi-project-4-api
  password: <%= ENV['WDI-PROJECT-4-API_DATABASE_PASSWORD'] %>
